### ISSUE TITLE
error in vignette data

### ISSUE THREAD

**Issue by wcjochem** [wpgp/foot#36]
A new error now appears when installing and building vignettes related to geometry errors in the sample dataset. Possibly due to a change in GEOS.

Workarounds: Install the package and don't build the vignettes. Or the dataset can be repaired with `st_make_valid()` and the examples will run.

To-Do: clean the sample dataset and rebuild package source.

**Comment by edarin** [comment]
I think it's due to the new version of `sf` that relies on `s2` package. https://r-spatial.github.io/sf/news/index.html#version-1-0-0-2021-06-09
