### ISSUE TITLE
nndist not functioning 

### ISSUE THREAD

**Issue by tilahunmulatu** [wpgp/foot#37]
I was using two separate metrics for my analysis (compact and nndist). Compact give me good results while nndist keep on returning NA values for all the study area. I was wondering why nndist is not functioning in my case? just to give more info  I am using these metrics to understand urban growth pattern in Detroit metropolitan regions. I am using very large building footprint dataset for the analysis.

**Comment by wcjochem** [comment]
Hi, it's hard to tell from your description what could be causing the problem. Can you please provide more information, including the command you are running and the results of `sessionInfo()`? Thanks.

**Comment by wcjochem** [comment]
I hope this latest update resolves this issue. If not, please re-open this. Thanks.
