### ISSUE TITLE
No internal check for crs in bigfoot

### ISSUE THREAD

**Issue by edarin** [wpgp/foot#40]
Inputs (mastergrid and building footprints layers) have to be provided in the same geographic coordinate system for the function work.

This should :
- either be detailed in the function manual or
- trigger a warning or
- trigger internally a projection to the same crs

**Comment by wcjochem** [comment]
Thanks for the report! Currently this throws an error and stops execution. I believe that is the correct behavior. It should not be a warning and users should have to choose how to re-project their data.

I do agree it could be a more graceful error with a more informative message for users. I'll add a check earlier in the processing. 

Reproducible example:
`data("kampala", package="foot")

buildings <- kampala$buildings
buildings <- st_transform(buildings, 32636)

templateGrid <- kampala$mastergrid

calculate_bigfoot(X=buildings,
                  what=list(list("shape"), list("perimeter")),
                  how=list(list("mean"), list("sum")),
                  controlUnits=list(areaUnit="m^2"),
                  filter = list(minArea=50,  # footprints must be larger than 50 m^2
                                maxArea=1000),  # footprints must be smaller than 1000 m^2
                  template=templateGrid, 
                  outputPath=tempdir(),  
                  outputTag="kampala",
                  parallel=FALSE,
                  verbose=TRUE)  `
