### ISSUE TITLE
Combining polygons that are within a specified distance of each other into a new polygon

### ISSUE THREAD

**Issue by fgoerlich** [wpgp/foot#46]
Does `foot` allows to combine buildings in a similar fashion that the [Aggregate Polygons](https://pro.arcgis.com/en/pro-app/latest/tool-reference/cartography/aggregate-polygons.htm) tool of ArcGIS?
![image](https://user-images.githubusercontent.com/6486324/199813112-3633866f-d175-442f-b389-32eeab833a17.png)

More information, and a detailed example, with some data in this `sf` [issue](https://github.com/r-spatial/sf/issues/2022),
Thanks a lot.

**Comment by wcjochem** [comment]
Hi @fgoerlich, this functionality is not part of `foot`. The reply you got in the issue you linked to seem like the best approach you can take. Thanks.
